export const SET_SOURCE_AMOUNT = 'SET_SOURCE_AMOUNT';
export const SET_SOURCE_CURRENCY = 'SET_SOURCE_CURRENCY';
export const SET_TARGET_CURRENCY = 'SET_TARGET_CURRENCY';
export const FETCH_EXCHANGE_RATE_REQUESTED = 'FETCH_EXCHANGE_RATE_REQUESTED';
export const FETCH_EXCHANGE_RATE_SUCCEEDED = 'FETCH_EXCHANGE_RATE_SUCCEDDED';
export const FETCH_EXCHANGE_RATE_FAILED = 'FETCH_EXCHANGE_RATE_FAILED';