export const physicalCurrencies = {
	"United Arab Emirates Dirham": "AED",
	"Afghan Afghani": "AFN",
	"Albanian Lek": "ALL",
	"Armenian Dram": "AMD",
	"Netherlands Antillean Guilder": "ANG",
	"Angolan Kwanza": "AOA",
	"Argentine Peso": "ARS",
	"Australian Dollar": "AUD",
	"Aruban Florin": "AWG",
	"Azerbaijani Manat": "AZN",
	"Bosnia-Herzegovina Convertible Mark": "BAM",
	"Barbadian Dollar": "BBD",
	"Bangladeshi Taka": "BDT",
	"Bulgarian Lev": "BGN",
	"Bahraini Dinar": "BHD",
	"Burundian Franc": "BIF",
	"Bermudan Dollar": "BMD",
	"Brunei Dollar": "BND",
	"Bolivian Boliviano": "BOB",
	"Brazilian Real": "BRL",
	"Bahamian Dollar": "BSD",
	"Bhutanese Ngultrum": "BTN",
	"Botswanan Pula": "BWP",
	"Belize Dollar": "BZD",
	"Canadian Dollar": "CAD",
	"Congolese Franc": "CDF",
	"Swiss Franc": "CHF",
	"Chilean Unit of Account UF": "CLF",
	"Chilean Peso": "CLP",
	"Chinese Yuan Offshore": "CNH",
	"Chinese Yuan": "CNY",
	"Colombian Peso": "COP",
	"Cuban Peso": "CUP",
	"Cape Verdean Escudo": "CVE",
	"Czech Republic Koruna": "CZK",
	"Djiboutian Franc": "DJF",
	"Danish Krone": "DKK",
	"Dominican Peso": "DOP",
	"Algerian Dinar": "DZD",
	"Egyptian Pound": "EGP",
	"Eritrean Nakfa": "ERN",
	"Ethiopian Birr": "ETB",
	"Euro": "EUR",
	"Fijian Dollar": "FJD",
	"Falkland Islands Pound": "FKP",
	"British Pound Sterling": "GBP",
	"Georgian Lari": "GEL",
	"Ghanaian Cedi": "GHS",
	"Gibraltar Pound": "GIP",
	"Gambian Dalasi": "GMD",
	"Guinean Franc": "GNF",
	"Guatemalan Quetzal": "GTQ",
	"Guyanaese Dollar": "GYD",
	"Hong Kong Dollar": "HKD",
	"Honduran Lempira": "HNL",
	"Croatian Kuna": "HRK",
	"Haitian Gourde": "HTG",
	"Hungarian Forint": "HUF",
	"Indonesian Rupiah": "IDR",
	"Israeli New Sheqel": "ILS",
	"Indian Rupee": "INR",
	"Iraqi Dinar": "IQD",
	"Iranian Rial": "IRR",
	"Icelandic Krona": "ISK",
	"Jersey Pound": "JEP",
	"Jamaican Dollar": "JMD",
	"Jordanian Dinar": "JOD",
	"Japanese Yen": "JPY",
	"Kenyan Shilling": "KES",
	"Kyrgystani Som": "KGS",
	"Cambodian Riel": "KHR",
	"Comorian Franc": "KMF",
	"North Korean Won": "KPW",
	"South Korean Won": "KRW",
	"Kuwaiti Dinar": "KWD",
	"Cayman Islands Dollar": "KYD",
	"Kazakhstani Tenge": "KZT",
	"Laotian Kip": "LAK",
	"Lebanese Pound": "LBP",
	"Sri Lankan Rupee": "LKR",
	"Liberian Dollar": "LRD",
	"Lesotho Loti": "LSL",
	"Libyan Dinar": "LYD",
	"Moroccan Dirham": "MAD",
	"Moldovan Leu": "MDL",
	"Malagasy Ariary": "MGA",
	"Macedonian Denar": "MKD",
	"Myanma Kyat": "MMK",
	"Mongolian Tugrik": "MNT",
	"Macanese Pataca": "MOP",
	"Mauritanian Ouguiya (pre-2018)": "MRO",
	"Mauritanian Ouguiya": "MRU",
	"Mauritian Rupee": "MUR",
	"Maldivian Rufiyaa": "MVR",
	"Malawian Kwacha": "MWK",
	"Mexican Peso": "MXN",
	"Malaysian Ringgit": "MYR",
	"Mozambican Metical": "MZN",
	"Namibian Dollar": "NAD",
	"Nigerian Naira": "NGN",
	"Norwegian Krone": "NOK",
	"Nepalese Rupee": "NPR",
	"New Zealand Dollar": "NZD",
	"Omani Rial": "OMR",
	"Panamanian Balboa": "PAB",
	"Peruvian Nuevo Sol": "PEN",
	"Papua New Guinean Kina": "PGK",
	"Philippine Peso": "PHP",
	"Pakistani Rupee": "PKR",
	"Polish Zloty": "PLN",
	"Paraguayan Guarani": "PYG",
	"Qatari Rial": "QAR",
	"Romanian Leu": "RON",
	"Serbian Dinar": "RSD",
	"Russian Ruble": "RUB",
	"Old Russian Ruble": "RUR",
	"Rwandan Franc": "RWF",
	"Saudi Riyal": "SAR",
	"Solomon Islands Dollar": "SBDf",
	"Seychellois Rupee": "SCR",
	"Sudanese Pound": "SDG",
	"Special Drawing Rights": "SDR",
	"Swedish Krona": "SEK",
	"Singapore Dollar": "SGD",
	"Saint Helena Pound": "SHP",
	"Sierra Leonean Leone": "SLL",
	"Somali Shilling": "SOS",
	"Surinamese Dollar": "SRD",
	"Syrian Pound": "SYP",
	"Swazi Lilangeni": "SZL",
	"Thai Baht": "THB",
	"Tajikistani Somoni": "TJS",
	"Turkmenistani Manat": "TMT",
	"Tunisian Dinar": "TND",
	"Tongan Pa'anga": "TOP",
	"Turkish Lira": "TRY",
	"Trinidad and Tobago Dollar": "TTD",
	"New Taiwan Dollar": "TWD",
	"Tanzanian Shilling": "TZS",
	"Ukrainian Hryvnia": "UAH",
	"Ugandan Shilling": "UGX",
	"United States Dollar": "USD",
	"Uruguayan Peso": "UYU",
	"Uzbekistan Som": "UZS",
	"Vietnamese Dong": "VND",
	"Vanuatu Vatu": "VUV",
	"Samoan Tala": "WST",
	"CFA Franc BEAC": "XAF",
	"East Caribbean Dollar": "XCD",
	"CFA Franc BCEAO": "XOF",
	"CFP Franc": "XPF",
	"Yemeni Rial": "YER",
	"South African Rand": "ZAR",
	"Zambian Kwacha": "ZMW",
	"Zimbabwean Dollar": "ZWL"
}

export const cryptoCurrencies = {
	"FirstBlood": "1ST",
	"GiveCoin": "2GIVE",
	"808Coin": "808",
	"ArcBlock": "ABT",
	"ArtByte": "ABY",
	"AsiaCoin": "AC",
	"Achain": "ACT",
	"Cardano": "ADA",
	"adToken": "ADT",
	"AdEx": "ADX",
	"Aeternity": "AE",
	"Aeon": "AEON",
	"SingularityNET": "AGI",
	"IDNI-Agoras": "AGRS",
	"POLY-AI": "AI",
	"AidCoin": "AID",
	"Aion": "AION",
	"AirToken": "AIR",
	"Akuya-Coin": "AKY",
	"ALIS": "ALIS",
	"AmberCoin": "AMBER",
	"Synereo": "AMP",
	"Ampleforth": "AMPL",
	"Anoncoin": "ANC",
	"Aragon": "ANT",
	"AppCoins": "APPC",
	"APX-Ventures": "APX",
	"Ardor": "ARDR",
	"Ark": "ARK",
	"Aeron": "ARN",
	"AirSwap": "AST",
	"ATBCoin": "ATB",
	"ATMChain": "ATM",
	"Authorship": "ATS",
	"Auroracoin": "AUR",
	"Aventus": "AVT",
	"B3Coin": "B3",
	"Basic-Attention-Token": "BAT",
	"BitBay": "BAY",
	"Boolberry": "BBR",
	"BCAP": "BCAP",
	"BitConnect": "BCC",
	"Bitcoin-Diamond": "BCD",
	"Bitcoin-Cash": "BCH",
	"Bytecoin": "BCN",
	"BlockMason-Credit-Protocol-Token": "BCPT",
	"BitcoinX": "BCX",
	"BitCrystals": "BCY",
	"Bitdeal": "BDL",
	"Bee-Token": "BEE",
	"BelaCoin": "BELA",
	"DAO-Casino": "BET",
	"BF-Token": "BFT",
	"Bismuth": "BIS",
	"BitBean": "BITB",
	"BitBTC": "BITBTC",
	"BitCNY": "BITCNY",
	"BitEUR": "BITEUR",
	"BitGOLD": "BITGOLD",
	"BitSILVER": "BITSILVER",
	"BitUSD": "BITUSD",
	"Bibox-Token": "BIX",
	"Blitzcash": "BLITZ",
	"Blackcoin": "BLK",
	"Bolenum": "BLN",
	"Blocknet": "BLOCK",
	"Bluzelle": "BLZ",
	"Blackmoon-Crypto": "BMC",
	"Binance-Coin": "BNB",
	"Bancor-Network-Token": "BNT",
	"Bounty0x": "BNTY",
	"BoostCoin": "BOST",
	"Bodhi": "BOT",
	"bitqy": "BQ",
	"Bread": "BRD",
	"Breakout-Coin": "BRK",
	"Breakout-Stake": "BRX",
	"Bata": "BTA",
	"Bitcoin": "BTC",
	"BitcoinDark": "BTCD",
	"Bitcoin-Private": "BTCP",
	"Bitcoin-Gold": "BTG",
	"Bitmark": "BTM",
	"BitShares": "BTS",
	"BTSR": "BTSR",
	"Bitcore": "BTX",
	"Burstcoin": "BURST",
	"Binance-USD": "BUSD",
	"BuzzCoin": "BUZZ",
	"Bytecent": "BYC",
	"Bytom": "BYTOM",
	"Crypto20": "C20",
	"CannabisCoin": "CANN",
	"BlockCAT": "CAT",
	"CryptoCarbon": "CCRB",
	"Blox": "CDT",
	"Cofound-it": "CFI",
	"ChatCoin": "CHAT",
	"Chips": "CHIPS",
	"Clams": "CLAM",
	"CloakCoin": "CLOAK",
	"Compcoin": "CMP",
	"CyberMiles": "CMT",
	"Cindicator": "CND",
	"Cryptonex": "CNX",
	"CoinFi": "COFI",
	"COSS": "COSS",
	"Circuits-Of-Value": "COVAL",
	"CreditBIT": "CRBIT",
	"CreativeCoin": "CREA",
	"Credo": "CREDO",
	"Crown": "CRW",
	"BitDice": "CSNO",
	"Centra": "CTR",
	"Cortex": "CTXC",
	"CureCoin": "CURE",
	"Civic": "CVC",
	"Dai": "DAI",
	"Darcrus": "DAR",
	"Dash": "DASH",
	"DATAcoin": "DATA",
	"Chronologic": "DAY",
	"DeepBrain-Chain": "DBC",
	"DubaiCoin": "DBIX",
	"Dentacoin": "DCN",
	"Decred": "DCR",
	"DECENT": "DCT",
	"Digital-Developers-Fund": "DDF",
	"Dent": "DENT",
	"DFSCoin": "DFS",
	"DigiByte": "DGB",
	"Digitalcoin": "DGC",
	"DigixDAO": "DGD",
	"Etheroll": "DICE",
	"Agrello-Delta": "DLT",
	"Diamond": "DMD",
	"DMarket": "DMT",
	"district0x": "DNT",
	"DogeCoin": "DOGE",
	"DopeCoin": "DOPE",
	"Dragonchain": "DRGN",
	"Data": "DTA",
	"Databits": "DTB",
	"Dynamic": "DYN",
	"EarthCoin": "EAC",
	"eBoost": "EBST",
	"eBTC": "EBTC",
	"ECC": "ECC",
	"E-coin": "ECN",
	"Edgeless": "EDG",
	"Eidoo": "EDO",
	"Electronic-Gulden": "EFL",
	"EverGreenCoin": "EGC",
	"EDUCare": "EKT",
	"Elastos": "ELA",
	"Electrify.Asia": "ELEC",
	"aelf": "ELF",
	"Elixir": "ELIX",
	"Embercoin": "EMB",
	"Emercoin": "EMC",
	"Einsteinium": "EMC2",
	"Enigma": "ENG",
	"Enjin-Coin": "ENJ",
	"EnergyCoin": "ENRG",
	"EOS": "EOS",
	"EOT-Token": "EOT",
	"EquiTrader": "EQT",
	"EuropeCoin": "ERC",
	"Ethereum-Classic": "ETC",
	"Ethereum": "ETH",
	"Ethereum-Dark": "ETHD",
	"Ethos": "ETHOS",
	"Electroneum": "ETN",
	"Metaverse-Entropy": "ETP",
	"EncryptoTel": "ETT",
	"Devery": "EVE",
	"Everex": "EVX",
	"ExclusiveCoin": "EXCL",
	"Expanse": "EXP",
	"Factom": "FCT",
	"FoldingCoin": "FLDC",
	"FlorinCoin": "FLO",
	"FlutterCoin": "FLT",
	"FirstCoin": "FRST",
	"Feathercoin": "FTC",
	"Etherparty": "FUEL",
	"FunFair": "FUN",
	"Gambit": "GAM",
	"GameCredits": "GAME",
	"Gas": "GAS",
	"Golos Gold": "GBG",
	"GoByte": "GBX",
	"Byteball": "GBYTE",
	"GCRCoin": "GCR",
	"GeoCoin": "GEO",
	"GoldCoin": "GLD",
	"Gnosis-Token": "GNO",
	"Golem-Tokens": "GNT",
	"Golos": "GOLOS",
	"Gridcoin": "GRC",
	"Groestlcoin": "GRS",
	"Growers-International": "GRWI",
	"Game": "GTC",
	"Gifto": "GTO",
	"Guppy": "GUP",
	"Genesis-Vision": "GVT",
	"GXShares": "GXS",
	"HoboNickels": "HBN",
	"HEAT": "HEAT",
	"Humaniq": "HMQ",
	"High-Performance-Blockchain": "HPB",
	"Hshare": "HSR",
	"Hush": "HUSH",
	"Hive": "HVN",
	"HexxCoin": "HXX",
	"ICONOMI": "ICN",
	"ICON": "ICX",
	"Infinitecoin": "IFC",
	"investFeed": "IFT",
	"Ignis": "IGNIS",
	"Incent": "INCNT",
	"Indorse-Token": "IND",
	"InfChain": "INF",
	"Ink": "INK",
	"INS-Ecosystem": "INS",
	"Insights-Network": "INSTAR",
	"Internet-Node-Token": "INT",
	"Internxt": "INXT",
	"IOCoin": "IOC",
	"ION": "ION",
	"Internet-of-People": "IOP",
	"IOStoken": "IOST",
	"IOTA": "IOTA",
	"IoTeX": "IOTX",
	"Iquant-Chain": "IQT",
	"IoT-Chain": "ITC",
	"iXcoin": "IXC",
	"InsureX": "IXT",
	"JET8": "J8T",
	"Jibrel-Network": "JNT",
	"KuCoin": "KCS",
	"KickCoin": "KICK",
	"KIN": "KIN",
	"Komodo": "KMD",
	"Kyber-Network": "KNC",
	"KoreCoin": "KORE",
	"LBRY-Credits": "LBC",
	"Litecoin-Cash": "LCC",
	"EthLend": "LEND",
	"Leverj": "LEV",
	"Legends-Room": "LGD",
	"Linda": "LINDA",
	"ChainLink": "LINK",
	"Lykke": "LKK",
	"LoMoCoin": "LMC",
	"LOCIcoin": "LOCI",
	"Loom-Token": "LOOM",
	"Loopring": "LRC",
	"Lisk": "LSK",
	"Litecoin": "LTC",
	"Lunyr": "LUN",
	"MaidSafeCoin": "MAID",
	"Decentraland": "MANA",
	"Maxcoin": "MAX",
	"Embers": "MBRS",
	"MCAP": "MCAP",
	"Monaco": "MCO",
	"Moeda-Loyalty-Points": "MDA",
	"Megacoin": "MEC",
	"MediBlock": "MED",
	"Memetic": "MEME",
	"Mercury": "MER",
	"MergeCoin": "MGC",
	"MobileGo": "MGO",
	"Minex": "MINEX",
	"Mintcoin": "MINT",
	"Mithril": "MITH",
	"Maker": "MKR",
	"Melon": "MLN",
	"Minereum": "MNE",
	"MinexCoin": "MNX",
	"Modum": "MOD",
	"MonaCoin": "MONA",
	"Miners-Reward-Token": "MRT",
	"Mothership": "MSP",
	"Monetha": "MTH",
	"MedToken": "MTN",
	"MonetaryUnit": "MUE",
	"Musicoin": "MUSIC",
	"MyBit-Token": "MYB",
	"Mysterium": "MYST",
	"Mazacoin": "MZC",
	"Namocoin": "NAMO",
	"Nano": "NANO",
	"Nebulas-Token": "NAS",
	"Nav-Coin": "NAV",
	"NuBits": "NBT",
	"Nucleus-Vision": "NCASH",
	"NeverDie-Coin": "NDC",
	"Neblio": "NEBL",
	"NEO": "NEO",
	"NeosCoin": "NEOS",
	"Nimiq": "NET",
	"NoLimitCoin": "NLC2",
	"Gulden": "NLG",
	"Namecoin": "NMC",
	"Numeraire": "NMR",
	"NobleCoin": "NOBL",
	"DNotes": "NOTE",
	"Pundi-X-Token": "NPXS",
	"NuShares": "NSR",
	"Fujinto": "NTO",
	"Nuls": "NULS",
	"Novacoin": "NVC",
	"Nexium": "NXC",
	"Nexus": "NXS",
	"Nxt": "NXT",
	"openANX": "OAX",
	"Obits": "OBITS",
	"Oceanlab": "OCL",
	"Odyssey": "OCN",
	"ODEM": "ODEM",
	"Obsidian": "ODN",
	"OFCOIN": "OF",
	"OKCash": "OK",
	"OmiseGo": "OMG",
	"Omni": "OMNI",
	"DeepOnion": "ONION",
	"Ontology": "ONT",
	"Opus": "OPT",
	"Simple-Token": "OST",
	"Particl": "PART",
	"PascalCoin": "PASC",
	"TenX": "PAY",
	"Pebbles": "PBL",
	"Primalbase-Token": "PBT",
	"Payfair": "PFR",
	"CryptoPing": "PING",
	"Pinkcoin": "PINK",
	"PIVX": "PIVX",
	"Lampix": "PIX",
	"Polybius": "PLBT",
	"Pillar": "PLR",
	"Pluton": "PLU",
	"POA-Network": "POA",
	"Poet": "POE",
	"Polymath": "POLY",
	"PoSW-Coin": "POSW",
	"PotCoin": "POT",
	"Power-Ledger": "POWR",
	"Peercoin": "PPC",
	"Populous": "PPT",
	"Peerplays": "PPY",
	"Paragon-Coin": "PRG",
	"Oyster-Pearl": "PRL",
	"Propy": "PRO",
	"Primas": "PST",
	"Pesetacoin": "PTC",
	"Patientory": "PTOY",
	"Pura": "PURA",
	"QASH": "QASH",
	"Quantum": "QAU",
	"Qlink": "QLC",
	"Quark": "QRK",
	"Quantum-Resistant-Ledger": "QRL",
	"Quantstamp": "QSP",
	"Quatloo": "QTL",
	"Qtum": "QTUM",
	"Qwark": "QWARK",
	"Revain": "R",
	"Radium": "RADS",
	"Condensate": "RAIN",
	"Rubies": "RBIES",
	"Ripto-Bux": "RBX",
	"RubyCoin": "RBY",
	"Ripio-Credit-Network": "RCN",
	"ReddCoin": "RDD",
	"Raiden-Network-Token": "RDN",
	"Regalcoin": "REC",
	"Redcoin": "RED",
	"Augur": "REP",
	"Request-Network": "REQ",
	"RChain": "RHOC",
	"Riecoin": "RIC",
	"Rise": "RISE",
	"RLC-Token": "RLC",
	"RouletteToken": "RLT",
	"Red-Pulse": "RPX",
	"Recovery-Right-Tokens": "RRT",
	"Ruff": "RUFF",
	"Rupee": "RUP",
	"Rivetz": "RVT",
	"SafeExchangeCoin": "SAFEX",
	"Salt": "SALT",
	"Santiment-Network-Token": "SAN",
	"Steem-Dollars": "SBD",
	"Super-Bitcoin": "SBTC",
	"Siacoin": "SC",
	"Seele": "SEELE",
	"Sequence": "SEQ",
	"SHIFT": "SHIFT",
	"SIBCoin": "SIB",
	"SIGMAcoin": "SIGMA",
	"Signatum": "SIGT",
	"Storjcoin-X": "SJCX",
	"SkinCoin": "SKIN",
	"Skycoin": "SKY",
	"SolarCoin": "SLR",
	"SaluS": "SLS",
	"SmartCash": "SMART",
	"SmartMesh": "SMT",
	"SunContract": "SNC",
	"SingularDTV": "SNGLS",
	"SONM": "SNM",
	"Synergy": "SNRG",
	"Status-Network-Token": "SNT",
	"All-Sports": "SOC",
	"Phantasma": "SOUL",
	"SpankChain": "SPANK",
	"SpaceChain": "SPC",
	"Sphere": "SPHR",
	"SpreadCoin": "SPR",
	"Synthetix-Network-Token": "SNX",
	"Sirin-Labs-Token": "SRN",
	"Startcoin": "START",
	"Steem": "STEEM",
	"STK-Token": "STK",
	"Storj": "STORJ",
	"Storm": "STORM",
	"Storiqa": "STQ",
	"Stratis": "STRAT",
	"Stox": "STX",
	"Substratum": "SUB",
	"SwftCoin": "SWFTC",
	"Bitswift": "SWIFT",
	"Swarm-City": "SWT",
	"Syndicate": "SYNX",
	"SysCoin": "SYS",
	"Taas": "TAAS",
	"Lamden": "TAU",
	"The-ChampCoin": "TCC",
	"True-Flip": "TFL",
	"HempCoin": "THC",
	"Theta-Token": "THETA",
	"Time": "TIME",
	"Blocktix": "TIX",
	"TokenCard": "TKN",
	"Trackr": "TKR",
	"Tokes": "TKS",
	"Time-New-Bank": "TNB",
	"Tierion": "TNT",
	"ToaCoin": "TOA",
	"OriginTrail": "TRAC",
	"Terracoin": "TRC",
	"Tracto": "TRCT",
	"Triggers": "TRIG",
	"Trustcoin": "TRST",
	"TrueChain": "TRUE",
	"TrustPlus": "TRUST",
	"Tronix": "TRX",
	"TrueUSD": "TUSD",
	"TransferCoin": "TX",
	"Ubiq": "UBQ",
	"UnikoinGold": "UKG",
	"Ulatech": "ULA",
	"UnbreakableCoin": "UNB",
	"SuperNET": "UNITY",
	"Unobtanium": "UNO",
	"Unity-Ingot": "UNY",
	"UpToken": "UP",
	"Uro": "URO",
	"Tether": "USDT",
	"UTrust": "UTK",
	"BLOCKv": "VEE",
	"VeChain": "VEN",
	"Veritaseum": "VERI",
	"Viacoin": "VIA",
	"Viberate": "VIB",
	"Vibe": "VIBE",
	"VIVO": "VIVO",
	"Voise": "VOISE",
	"Voxels": "VOX",
	"VPNCoin": "VPN",
	"Vericoin": "VRC",
	"Verium": "VRM",
	"Veros": "VRS",
	"vSlice": "VSL",
	"Vertcoin": "VTC",
	"vTorrent": "VTR",
	"WaBi": "WABI",
	"Wanchain": "WAN",
	"Waves": "WAVES",
	"Wax-Token": "WAX",
	"Waves-Community": "WCT",
	"WorldCoin": "WDC",
	"WavesGo": "WGO",
	"Wagerr": "WGR",
	"Wings": "WINGS",
	"WePower": "WPR",
	"Walton": "WTC",
	"Giga-Watt-Token": "WTT",
	"Asch": "XAS",
	"Xaurum": "XAUR",
	"Bitcoin-Plus": "XBC",
	"XtraBYtes": "XBY",
	"Cryptonite": "XCN",
	"Counterparty": "XCP",
	"DigitalNote": "XDN",
	"Elastic": "XEL",
	"NEM": "NEM",
	"Haven-Protocol": "XHV",
	"Sphere-Identity": "XID",
	"Stellar": "XLM",
	"Magi": "XMG",
	"Monero": "XMR",
	"Metal": "XMT",
	"Myriadcoin": "XMY",
	"Primecoin": "XPM",
	"Rialto": "XRL",
	"Ripple": "XRP",
	"Spectrecoin": "XSPEC",
	"Stealthcoin": "XST",
	"Tezos": "XTZ",
	"Exchange-Union": "XUC",
	"Vcash": "XVC",
	"Verge": "XVG",
	"WhiteCoin": "XWC",
	"ZCoin": "XZC",
	"ZrCoin": "XZR",
	"Yee": "YEE",
	"YOYOW": "YOYOW",
	"ZcCoin": "ZCC",
	"Zclassic": "ZCL",
	"Zebi": "ZCO",
	"Zcash": "ZEC",
	"ZenCash": "ZEN",
	"Zetacoin": "ZET",
	"Zilliqa": "ZIL",
	"Zilla": "ZLA",
	"0x": "ZRX"
}	